config/routes.rb
Rails.application.routes.draw do
  resources :tweets
  resources :friendships
  resources :posts
  resources :profiles
  resources :photos
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy ]

  # GET /tweets or /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: "Tweet was successfully created." }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy!

    respond_to do |format|
      format.html { redirect_to tweets_path, status: :see_other, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:user_id, :content)
    end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.erb
<%= form_with(model: tweet) do |form| %>
  <% if tweet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.hidden_field :user_id,value: current_user.try(:id) %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_field :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
          <div class='col-md-4 mb-3'>
            <div class='card'>
              <div class='card-body'>
                <h5 class='card-title'>User <%= tweet.user_id %></h5>
                <p class='card-text'><%= tweet.content %></p>
                <small class='text-muted'><%= tweet.created_at.strftime('%B %d, %Y') %></small>
              </div>
            </div>
          </div>

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Show this tweet", @tweet %> |
  <%= link_to "Back to tweets", tweets_path %>
</div>

app/views/tweets/index.html.erb
<div class='container mt-4'>
      <h1 class='mb-4'>Tweets</h1>
      <div class='row'>
        <% @tweets.each do |tweet| %>
          <div class='col-md-4 mb-3'>
            <div class='card'>
              <div class='card-body'>
                <h5 class='card-title'>User <%= tweet.user_id %></h5>
                <p class='card-text'><%= tweet.content %></p>
                <small class='text-muted'><%= tweet.created_at.strftime('%B %d, %Y') %></small>
                <small class='text-muted'><%= link_to "voir tweet",tweet %></small>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      </div>
<%=link_to "nouveau tweet",new_tweet_path%>

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Back to tweets", tweets_path %>
</div>

app/views/tweets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tweet %>


<div>
  <%= link_to "Edit this tweet", edit_tweet_path(@tweet) %> |
  <%= link_to "Back to tweets", tweets_path %>

  <%= button_to "Destroy this tweet", @tweet, method: :delete %>
</div>