config/routes.rb
Rails.application.routes.draw do
  resources :tweets
  resources :friendships
  resources :posts
  resources :profiles
  resources :photos
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User", foreign_key: "friend_id"
def self.types
[["friend",1],["family",2]]
end
def self.findtypes(x)
case x
when 1
"friend"
else
"family"
end
end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :set_friendship, only: %i[ show edit update destroy ]

  # GET /friendships or /friendships.json
  def index
    @friendships = Friendship.all
  end

  # GET /friendships/1 or /friendships/1.json
  def show
  end

  # GET /friendships/new
  def new
    @friendship = Friendship.new
  end

  # GET /friendships/1/edit
  def edit
  end

  # POST /friendships or /friendships.json
  def create
    @friendship = Friendship.new(friendship_params)

    respond_to do |format|
      if @friendship.save
        format.html { redirect_to @friendship, notice: "Friendship was successfully created." }
        format.json { render :show, status: :created, location: @friendship }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friendship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friendships/1 or /friendships/1.json
  def update
    respond_to do |format|
      if @friendship.update(friendship_params)
        format.html { redirect_to @friendship, notice: "Friendship was successfully updated." }
        format.json { render :show, status: :ok, location: @friendship }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friendship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friendships/1 or /friendships/1.json
  def destroy
    @friendship.destroy!

    respond_to do |format|
      format.html { redirect_to friendships_path, status: :see_other, notice: "Friendship was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friendship
      @friendship = Friendship.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friendship_params
      params.require(:friendship).permit(:user_id, :friend_id, :status)
    end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/_form.html.erb
<%= form_with(model: friendship) do |form| %>
  <% if friendship.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friendship.errors.count, "error") %> prohibited this friendship from being saved:</h2>

      <ul>
        <% friendship.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.hidden_field :user_id,value:current_user.try(:id) %>
  </div>

  <div>
    <%= form.label :friend_id, style: "display: block" %>
    <%= form.select :friend_id, User.all.pluck(:email,:id) %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.select :status, Friendship.types %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/friendships/_friendship.html.erb
        <div id="<%= dom_id(friendship) %>" class="card" style="width: 18rem;">
          <div class="card-body">

            <h5 class="card-title">email ami: <%= friendship.friend.email %></h5>
            <p class="card-text">mon email: <%= friendship.user.email %></p>
            <p class="card-text">statut: <%= Friendship.findtypes(friendship.status) %></p>
    <p>
      <%= link_to "Show this friendship", friendship %>
    </p>

          </div>
        </div>

app/views/friendships/edit.html.erb
<h1>Editing friendship</h1>

<%= render "form", friendship: @friendship %>

<br>

<div>
  <%= link_to "Show this friendship", @friendship %> |
  <%= link_to "Back to friendships", friendships_path %>
</div>

app/views/friendships/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Friendships</h1>


<div class="container">
  <div class="row">
    <% @friendships.each do |friendship| %>
      <div class="col-md-4">
        <div id="<%= dom_id(friendship) %>" class="card" style="width: 18rem;">
          <div class="card-body">

            <h5 class="card-title">email ami: <%= friendship.friend.email %></h5>
            <p class="card-text">mon email: <%= friendship.user.email %></p>
            <p class="card-text">statut: <%= Friendship.findtypes(friendship.status) %></p>
    <p>
      <%= link_to "Show this friendship", friendship %>
    </p>

          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<%= link_to "New friendship", new_friendship_path %>

app/views/friendships/new.html.erb
<h1>New friendship</h1>

<%= render "form", friendship: @friendship %>

<br>

<div>
  <%= link_to "Back to friendships", friendships_path %>
</div>

app/views/friendships/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @friendship %>

<div>
  <%= link_to "Edit this friendship", edit_friendship_path(@friendship) %> |
  <%= link_to "Back to friendships", friendships_path %>

  <%= button_to "Destroy this friendship", @friendship, method: :delete %>
</div>