config/routes.rb
Rails.application.routes.draw do
  resources :tweets
  resources :friendships
  resources :posts
  resources :profiles
  resources :photos
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
def image=(uploaded_io)
File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
  file.write(uploaded_io.read)
end
write_attribute(:image,uploaded_io.original_filename)

end
def self.image
read_attribute(:image)

end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: %i[ show edit update destroy ]

  # GET /photos or /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1 or /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos or /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: "Photo was successfully created." }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1 or /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: "Photo was successfully updated." }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1 or /photos/1.json
  def destroy
    @photo.destroy!

    respond_to do |format|
      format.html { redirect_to photos_path, status: :see_other, notice: "Photo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def photo_params
      params.require(:photo).permit(:user_id, :image, :caption)
    end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_with(model: photo) do |form| %>
  <% if photo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
        <% photo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.hidden_field :user_id,value: current_user.try(:id) %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.file_field :image %>
  </div>

  <div>
    <%= form.label :caption, style: "display: block" %>
    <%= form.text_area :caption %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/photos/_photo.html.erb
            <div class='card'>
              <img src="/uploads/<%= photo.image%>" class='card-img-top' alt="Photo">
              <div class='card-body'>
                <p class='card-text'><%= photo.caption %></p>
                <small class='text-muted'>Uploaded by: <%= photo.user.email %></small>
                <small class='text-muted'>Uploaded on: <%= photo.created_at.strftime('%B %d, %Y') %></small>
              </div>
            </div>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render "form", photo: @photo %>

<br>

<div>
  <%= link_to "Show this photo", @photo %> |
  <%= link_to "Back to photos", photos_path %>
</div>

app/views/photos/index.html.erb
<div class='container mt-4'>
      <h1 class='mb-4'>Instagram Photos</h1>
      <div class='row'>
        <% @photos.each do |photo| %>
          <div class='col-md-3 mb-3'>
            <div class='card'>
              <img src="/uploads/<%= photo.image%>" class='card-img-top' alt="Photo">
              <div class='card-body'>
                <p class='card-text'><%= photo.caption %></p>
                <small class='text-muted'>Uploaded on: <%= photo.created_at.strftime('%B %d, %Y') %></small>
      <p><%= link_to 'voir Photo', photo_path(photo.id), class: 'btn btn-success mt-4' %></p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <%= link_to 'new Photo', new_photo_path, class: 'btn btn-success mt-4' %>
      </div>
<%= link_to 'New photo', new_photo_path, class: 'btn btn-primary' %>

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render "form", photo: @photo %>

<br>

<div>
  <%= link_to "Back to photos", photos_path %>
</div>

app/views/photos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @photo %>

<div>
  <%= link_to "Edit this photo", edit_photo_path(@photo) %> |
  <%= link_to "Back to photos", photos_path %>

  <%= button_to "Destroy this photo", @photo, method: :delete %>
</div>