config/routes.rb
Rails.application.routes.draw do
  resources :tweets
  resources :friendships
  resources :posts
  resources :profiles
  resources :photos
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "posts#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>New Facebook Account</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
    <%#= javascript_include_tag 'application', 'data-turbo-track': 'reload', defer: true %>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">
  </head>

  <body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">New Facebook Account

&#128135;
/

&#129682;

/

&#129701;
&#129463;



</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav me-auto">
            <li class="nav-item">
              <%= link_to 'Tweets', tweets_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Friendships', friendships_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Posts', posts_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Profiles', profiles_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Photos', photos_path, class: 'nav-link' %>
            </li>
          </ul>

          <ul class="navbar-nav">
            <% if user_signed_in? %>
              <li class="nav-item">
                <a class="nav-link disabled" href="#">Logged in as: <%= current_user.email %></a>
              </li>
              <li class="nav-item">
                <%= button_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link' %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to 'Login', new_user_session_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Main Content -->
    <main class="container mt-4">
      <%= yield %>
    </main>

    <!-- Footer -->
    <footer class="bg-light text-center py-3 mt-4">
      <p>&copy; <%= Time.now.year %> New Facebook Account</p>
    </footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js" integrity="sha384-j1CDi7MgGQ12Z7Qab0qlWQ/Qqz24Gc6BM0thvEMVjHnfYGF0rmFCozFSxQBxwHKO" crossorigin="anonymous"></script>
  </body>
</html>